discourse_static_pages_sync:
  discourse_static_pages_sync_enabled:
    default: false
    client: true

  github_committer_username:
    default: ""
    type: string

  github_committer_email:
    default: ""
    type: email

  github_access_token:
    default: ""
    secret: true

  delete_post_file_when_post_deleted:
    default: true
    type: bool
