discourse_static_pages_sync:
  discourse_static_pages_sync_enabled:
    default: false
    client: true

  commit_message:
    default: "Sync topic with forum"
    type: string

  github_committer_username:
    default: ""
    type: string

  github_committer_email:
    default: ""
    type: email

  github_access_token:
    default: ""
    secret: true

  target_github_repo:
    default: ""
    type: string

  delete_post_file_when_post_deleted:
    default: true
    type: bool

  log_when_post_uploaded:
    default: false
    type: bool

  backfill_sync_topics_count:
    default: 200
    type: integer
    min: 1

  topic_post_template:
    default: |
      ---
      post_type: @{post_type}
      topic_name: @{topic_name}
      topic_id: @{topic_id}
      category: @{category_name}
      author: @{username}
      created_at: @{created_at}
      updated_at: @{updated_at}
      ---

      @{post_content}
    type: string
    textarea: true

  reply_post_template:
    default: |
      ---
      post_type: @{post_type}
      topic_name: @{topic_name}
      topic_id: @{topic_id}
      author: @{username}
      created_at: @{created_at}
      updated_at: @{updated_at}
      whisper: @{whisper}
      ---

      @{post_content}
    type: string
    textarea: true

  topic_post_path:
    default: "/@{category_slug}/@{topic_slug}.md"
    type: string
  
  reply_post_path:
    default: "/@{topic_slug}/@{post_number}.md"
    type: string

  allowed_categories:
    default: ""
    type: category
